name: test secret value at runtime

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set secret
        run: gh secret set MYSECRET --body "this is the value"
      - run: echo "${{secrets.MYSECRET}}"
