name: test secret value at runtime

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      # - name: set secret
      #   run: gh secret set MYSECRET --body "this is the value" --no-store
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      - run: |
          echo "::add-mask::my_plain_text_value" 
          echo "MY_SECRET=my_plain_text_value" >> $GITHUB_ENV
      - run: echo "${{env.MY_SECRET}}"
