name: test secret value at runtime

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set secret
        run: gh secret set MYSECRET --body "this is the value" --no-store
        env:
          GH_TOKEN: ${{ github.token }}
      - run: echo "${{secrets.MYSECRET}}"
